// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3drczRNnaKA95wt9kqfBh1OLFIDsNg2I',
    appId: '1:749153763094:web:9fa29514687a6846e25a37',
    messagingSenderId: '749153763094',
    projectId: 'tutor-finder-0468',
    authDomain: 'tutor-finder-0468.firebaseapp.com',
    databaseURL: 'https://tutor-finder-0468-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tutor-finder-0468.firebasestorage.app',
    measurementId: 'G-9J9X3F0J91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWJ7a6HxeaBgI7CuhpXUEYtciVmgDk1Gg',
    appId: '1:749153763094:android:46d5fb4a61466eb0e25a37',
    messagingSenderId: '749153763094',
    projectId: 'tutor-finder-0468',
    databaseURL: 'https://tutor-finder-0468-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tutor-finder-0468.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7GqA8OBNjB4AI8VrmEKFlk4gA5Hr7snY',
    appId: '1:749153763094:ios:7ebce93adc3f0e39e25a37',
    messagingSenderId: '749153763094',
    projectId: 'tutor-finder-0468',
    databaseURL: 'https://tutor-finder-0468-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tutor-finder-0468.firebasestorage.app',
    iosClientId: '749153763094-5ui0ms49komlv9tvsen0pr3aenodechg.apps.googleusercontent.com',
    iosBundleId: 'com.aunxbscs.tutorFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7GqA8OBNjB4AI8VrmEKFlk4gA5Hr7snY',
    appId: '1:749153763094:ios:7ebce93adc3f0e39e25a37',
    messagingSenderId: '749153763094',
    projectId: 'tutor-finder-0468',
    databaseURL: 'https://tutor-finder-0468-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tutor-finder-0468.firebasestorage.app',
    iosClientId: '749153763094-5ui0ms49komlv9tvsen0pr3aenodechg.apps.googleusercontent.com',
    iosBundleId: 'com.aunxbscs.tutorFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3drczRNnaKA95wt9kqfBh1OLFIDsNg2I',
    appId: '1:749153763094:web:d27a6fa05fd8aa00e25a37',
    messagingSenderId: '749153763094',
    projectId: 'tutor-finder-0468',
    authDomain: 'tutor-finder-0468.firebaseapp.com',
    databaseURL: 'https://tutor-finder-0468-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tutor-finder-0468.firebasestorage.app',
    measurementId: 'G-G4JF1QT7CS',
  );

}